### ISSUE TITLE
"Last updated" time stamp remains static for as long as the page is open

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#11]
If you keep the Routinator page open en you do several lookups over time, the "Last updated" timestamp does not refresh at any point. Only if you give the page a hard refresh you will see the correct date and time.

**Comment by density215** [comment]
I could long-poll the status endpoint every minute or so (kinda annoying for all systems involved) or the status endpoint should offer websockets (probably non-trivial over-engineering)

**Comment by density215** [comment]
The routinator status (including the last update datetime) now updates at each validation requested by the user.
