### ISSUE TITLE
Allow entering an IP address in the Prefix field

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#15]
Sometimes you don't know what the prefix is exactly, e.g. "is the BGP announcement that contains the IP of my webserver covered by a ROA?".

It would be nice to be able to simply enter an IP address in the interface and have the system look up the most specific announcement it can find that contains it, and then display the results.

**Comment by density215** [comment]
You can now enter an IP address, this will replace the prefix to be validated with the longest matching prefix that is either allocated or routed. You'll see an indication, underneath the prefix input field, that indicates the prefix has been inferred.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/986937/132542085-93399e4b-5646-4cd0-83aa-34d86655788f.png">

**Comment by AlexanderBand** [comment]
If the "this prefix was inferred" message has been triggered once, it will stay on screen even after doing a new query. Only refreshing the page will make it go away.

**Comment by density215** [comment]
fixes this

**Comment by density215** [comment]
this is now fixed
