### ISSUE TITLE
consider using a "valid" value as placeholder value

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator-ui#18]
As a user I want the placeholder to be valid input so that it works (e.g., no `e.g.`):

```html
<input type="text" autocomplete="off" placeholder="e.g. 192.0.2.0/24" required="required" class="el-input__inner">
```

**Comment by density215** [comment]
I don't actually think that is useful, since you can't submit, or even copy-paste a placeholder. The 'e.g.' indicates that this an actual example, not something you'd want to try
