### ISSUE TITLE
Could not proxy request 

### ISSUE THREAD

**Issue by Hristovnews** [NLnetLabs/routinator-ui#2]
Shame on me , but when i run the serv im getting :
Proxy error: Could not proxy request /api/v1/status from 10.64.10.31:8080 to https://localhost:3000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (EPROTO).

netstat -ltpn - there is no process to listen on port 3000 , 
/opt/routinator server  --http 127.0.0.1:8080 

What am i doing wrong ?

**Comment by partim** [comment]
Are you running a separate UI server or use the one included with Routinator?

**Comment by Hristovnews** [comment]
The one included with Routinator .

**Comment by enricoberti** [comment]
What if you change vue.config.js to match the same port of the routinator server?

`devServer: {
  proxy: 'https://localhost:8080'
}`

**Comment by Hristovnews** [comment]
I have tried this already , it is the same .
I have followed this guide for routinator install :
https://rpki.readthedocs.io/en/latest/routinator/installation-notes.html#selinux-using-centos-7
cat /etc/nginx/conf.d/ssl.conf 
server { some specifics }
    location / {
 {
        proxy_pass http://localhost:8080;
    }
    location /ui {
        proxy_pass http://127.0.0.1:8080/ui;
    }
    location /api {
        proxy_pass http://127.0.0.1:8080/api;
}
In order 'yarn run serve' to start on 8080 , i'm running /opt/routinator server     --http 127.0.0.1:8081

**Comment by partim** [comment]
So, assuming you have a Routinator instance running that listens on 127.0.0.1:8080, this nginx config means that UI should just be available under https://<yourhostname>/. You don’t need to run a separate Routinator for the UI.

**Comment by Hristovnews** [comment]
it is just one instance , without UI there was https://10.64.10.31/metrics# available . but it is like row statistics , that is why i follow this guide to install UI . After instalation of the UI https://10.64.10.31/metrics# i have the main page of the UI but statistics are "loading" and in the log on every refresh i get the Could not proxy request error .
I can start over as this is a test setup , but what i have to change in order to have routinator with UI behind nginx reverse proxy on one server .
BTW RTR session is working properly and is connected to a production router , forutnately the router has a second session to a Ripe rpki-validator , the goal  is to swap RIPE Rpki-validator and routinator has 10 times better performance over RIPEs one .

**Comment by partim** [comment]
Oh, I think I found the problem. I believe in your nginx config, you need to end the `proxy_pass` for the `/` location with a slash so that it redirects correctly. In this case _all_ Routinator endpoints will proxied though, which may not be what you want. Here’s what I have for my own test server to only allow select endpoints:

```
 server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	ssl_certificate /etc/letsencrypt/live/nate.do.nlnetlabs.nl/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/nate.do.nlnetlabs.nl/privkey.pem;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}

	location = / {
		proxy_pass http://127.0.0.1:8323/;
	}

	location /.well-known/acme-challenge/ {
		alias /var/run/acme/webroot/.well-known/acme-challenge/;
	}

	location /status {
		proxy_pass http://127.0.0.1:8323/status;
	}
	location /csv {
		proxy_pass http://127.0.0.1:8323/csv;
	}
	location /validity {
		proxy_pass http://127.0.0.1:8323/validity;
	}
	location /metrics {
		proxy_pass http://127.0.0.1:8323/metrics;
	}
	location /log {
		proxy_pass http://127.0.0.1:8323/log;
	}
	location /ui {
		proxy_pass http://127.0.0.1:8323/ui;
	}
	location /api {
		proxy_pass http://127.0.0.1:8323/api;
	}
}
```

Note the `location = /` rule. If you do this, you need the rules for `/ui` and `/api` for the UI to work.

**Comment by Hristovnews** [comment]
> Note the `location = /` rule. If you do this, you need the rules for `/ui` and `/api` for the UI to work.
Didn't help at first but :  
The problem was in vue.config.js , i've changed devServer: { proxy: '**https**://localhost:8080' } to http and now it is working properly . 
Thank you all for your help , now i am a happy little routinator .
