### ISSUE TITLE
`exact` has a lowercase E

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#20]
```
<text data-v-cfb18ddc="" x="379.043px" y="332.122px" style="font-family: BradleyHandITCTT-Bold, &quot;Bradley Hand&quot;; font-weight: 700; font-size: 12px;">  
exact  <---- THIS
</text>
```
<img width="460" alt="Screenshot 2021-07-06 at 15 51 52" src="https://user-images.githubusercontent.com/3448859/124612097-56460700-de72-11eb-96bc-88b1e4ba86db.png">

**Comment by density215** [comment]
Curious, that should have been curves only in the first place. This will never work if this font isn't installed system-wide.

**Comment by density215** [comment]
Replaced text with curves and capitalized exact
