### ISSUE TITLE
Make counters human readable

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#24]
Make counters - especially amount of data - scale better, i.e. don't just have "bytes". Also look at thousands separators, etc.

<img width="623" alt="Screenshot 2021-07-26 at 12 32 02" src="https://user-images.githubusercontent.com/3448859/126975241-caa0a006-06b7-427e-852a-03547db97284.png">

**Comment by AlexanderBand** [comment]
Did anything change here?

**Comment by density215** [comment]
Nothing. I've only changed it on the metrics page. You might want to review that first, I am not convinced it makes stuff better, thousands separators that is (based on locale). Better solution (but more involved) would be actual unit scales (like kb, mb, etc. where apprioriate),

**Comment by AlexanderBand** [comment]
Let's leave this open as a reminder until we find a good solution in the future.
