### ISSUE TITLE
Rename "Status" menu item

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#25]
It used to display the status, but now it's a "Validity Checker" or somesuch.

<img width="402" alt="Screenshot 2021-07-26 at 12 38 54" src="https://user-images.githubusercontent.com/3448859/126976090-0e386631-667f-4582-b99f-c4779b5d56d3.png">

**Comment by density215** [comment]
Renamed it to 'Prefix Check'
