### ISSUE TITLE
Column alignment off on less specifics

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#26]
<img width="1178" alt="Screenshot 2021-09-09 at 08 42 15" src="https://user-images.githubusercontent.com/3448859/132636029-7303f933-6a9a-47fd-be36-5774b33c2325.png">

**Comment by density215** [comment]
I can't do anything about this, unless I put back the (unused) caret on the left, in the less-specific table (in this case). This is a limitation of the element-ui framework.

**Comment by density215** [comment]
To be clear: this only happens when a less/more specific table only has one entry AND that entry is not validated (because there's no ASN to validate against)

**Comment by partim** [comment]
Pre 0.4.
