### ISSUE TITLE
v6 prefix triggers a "prefix was inferred message"

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#31]
I entered `2001:7fb::/32` and got a "this prefix was inferred"
<img width="523" alt="Screenshot 2021-09-13 at 19 01 49" src="https://user-images.githubusercontent.com/3448859/133126219-2c69b2f5-a775-4636-bf26-a890d9c96c32.png">

**Comment by density215** [comment]
Nothing. I've only changed it on the metrics page. You might want to review that first, I am not convinced it makes stuff better, thousands separators that is (based on locale). Better solution (but more involved) would be actual unit scales (like kb, mb, etc. where apprioriate),
