### ISSUE TITLE
Remove "RTR Total Connections"

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#33]
It displays no value because the metric was removed. So should the entry in the UI on the Connections page. I may have resolved this in https://github.com/NLnetLabs/routinator-ui/pull/5 but I'm not sure.

**Comment by density215** [comment]
The metric does exist in /api/v1/status under 'rtr' field. It is just filled with zeros. If there's no 'rtr' field in the output of that endpoint, the whole section RTR will also disappear.

Should I change the conditions to check if any of the contained values is bigger than 0?
