### ISSUE TITLE
Natural sort when sorting

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator-ui#35]
As a user I expect sorting a column to sort numbers to be sorted in "natural" increasing/descreasing order, not increasing/decreasing by string.

For example, I would expect 89 to be above 9 when sorting in descending order.
<img width="1432" alt="Screenshot 2021-09-16 at 17 32 57" src="https://user-images.githubusercontent.com/199058/133641431-8282099a-64b6-438f-b26f-d65a601ff07d.png">

**Comment by marlonbaeten** [comment]
Fixed on main.

**Comment by ties** [comment]
Thanks!
