### ISSUE TITLE
"Data Freshness" timestamps show 24 hours+

### ISSUE THREAD

**Issue by bluikko** [NLnetLabs/routinator-ui#40]
It is the first time I am seeing a timestamp such as `24:06:45 UTC` - shouldn't it be `00:06:45 UTC`? The "Data Freshness" shows such timestamps:
![image](https://user-images.githubusercontent.com/14869000/141045913-a81e6c1b-99d6-4986-8358-06fe2c2984e0.png)

Is this supposed to mean 00:06:45 UTC on 2021-11-09? Or is it a very mangled 00:06:45 UTC on 2021-11-08? It is confusing if it really is supposed to show timestamps over 24 hours.

**Comment by marlonbaeten** [comment]
Fixed on main.
