### ISSUE TITLE
Show "initial validation ongoing" message

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator-ui#9]
If you go to web interface after just starting Routinator, it just shows "Loading" with a spinner - it takes the web browser developer tools to actually find out that there's a call to API that results in 503 and "Initial validation ongoing. Please wait."

The UI should just show that message. See https://github.com/NLnetLabs/routinator/issues/448

**Comment by density215** [comment]
There's now both user messaging for routinator intializing and routinator failing. In both cases you can _still_ lookup less/more/allocs with roto.
